1st attempt at combining pip & conda jobs into single matrix

diff --git a/.github/workflows/conda-install.yml b/.github/workflows/conda-install.yml
--- a/.github/workflows/conda-install.yml
+++ b/.github/workflows/conda-install.yml
@@ -39,6 +39,21 @@ jobs:
             install-method: pip
             test-flags: --long-running
             install-c: false
+          - os: ubuntu-latest
+            python-version: 3.6
+            install-method: conda
+            test-flags: --long-running
+            install-c: true
+          - os: macos-latest
+            python-version: 3.6
+            install-method: conda
+            test-flags: --long-running
+            install-c: true
+          - os: windows-latest
+            python-version: 3.6
+            install-method: conda
+            test-flags: --long-running
+            install-c: true
       fail-fast: false
 
     steps:
@@ -46,55 +61,122 @@ jobs:
       with:
         submodules: true
     - name: Set C installation based on matrix value
-      if: matrix.install-c != true
+      if: matrix.install-c != true && matrix.install-method != 'conda'
       shell: bash -l {0}
       run: echo "INSTALLC=0" >> $GITHUB_ENV
-    - name: Patch TEMP/TMPDIR on Windows
+    - name: [WINDOWS] Patch TEMP/TMPDIR on Windows
       if: matrix.os == 'windows-latest' && matrix.install-method == 'pip'
       shell: bash -l {0}
       run: |
         echo "TMPDIR=$USERPROFILE\\AppData\\Local\\Temp" >> $GITHUB_ENV
         echo "TEMP=$USERPROFILE\\AppData\\Local\\Temp" >> $GITHUB_ENV
-    - name: Set VCPKG_ROOT on Windows
-      if: matrix.os == 'windows-latest' && matrix.install-method == 'pip' && env.INSTALLC == 1
-      shell: bash -l {0}
-      run: echo "VCPKG_ROOT=C:\\vcpkg" >> $GITHUB_ENV
-    - name: Set up MSVC Compiler
+    - name: [WINDOWS] Set up MSVC Compiler
       uses: ilammy/msvc-dev-cmd@v1
       if: matrix.os == 'windows-latest' && env.INSTALLC == 1
       with:
         toolset: 14.0
-    - name: Cache pip - Linux
+
+    # ========================================================
+    # Pip specific installation steps
+    # ========================================================
+    # - name: [WINDOWS,PIP] Set VCPKG_ROOT on Windows
+    #   if: matrix.os == 'windows-latest' && matrix.install-method == 'pip' && env.INSTALLC == 1
+    #   shell: bash -l {0}
+    #   run: echo "VCPKG_ROOT=C:\\vcpkg" >> $GITHUB_ENV
+    - name: [LINUX,PIP] Cache pip
       uses: actions/cache@v2
-      if: startsWith(runner.os, 'Linux')
+      if: startsWith(runner.os, 'Linux') && matrix.install-method == 'pip'
       with:
         path: ~/.cache/pip
         key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
         restore-keys: |
           ${{ runner.os }}-pip-
-    - name: Cache pip - MacOS
+    - name: [MACOS,PIP] Cache pip
       uses: actions/cache@v2
-      if: startsWith(runner.os, 'macOS')
+      if: startsWith(runner.os, 'macOS') && matrix.install-method == 'pip'
       with:
         path: ~/Library/Caches/pip
         key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
         restore-keys: |
           ${{ runner.os }}-pip-
-    - name: Cache pip - Windows
+    - name: [WINDOWS,PIP] Cache pip
       uses: actions/cache@v2
-      if: startsWith(runner.os, 'Windows')
+      if: startsWith(runner.os, 'Windows') && matrix.install-method == 'pip'
       with:
         path: ~\AppData\Local\pip\Cache
         key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
         restore-keys: |
           ${{ runner.os }}-pip-
-    - name: Set up Python
+    - name: [PIP] Set up Python
       uses: actions/setup-python@v2
       if: matrix.install-method == 'pip'
       with:
         python-version: ${{ matrix.python-version }}
-    - name: Install dependencies
+    - name: [PIP] Install dependencies & package
+      if: matrix.install-method == 'pip'
       run: python utils/setup_test_env.py install ${{ matrix.install-method }}
+    # ========================================================
+
+    # ========================================================
+    # Conda specific installation steps
+    # ========================================================
+    - name: [CONDA] Cache conda
+      uses: actions/cache@v1
+      if: matrix.install-method == 'conda'
+      env:
+        # Increase this value to reset cache if file not changed
+        CACHE_NUMBER: 0
+      with:
+        path: ~/conda_pkgs_dir
+        key:
+          ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{
+          hashFiles('recipe/meta.yaml') }}
+    - name: [WINDOWS,CONDA] Set up miniconda base environment
+      uses: conda-incubator/setup-miniconda@v2
+      if: matrix.install-method == 'conda' && matrix.os == 'windows-latest'
+      with:
+        channels: conda-forge
+        use-only-tar-bz2: true
+        activate-environment: ''
+        # auto-activate-base: false
+    # This step might need to stay here so that dev prompt comes before
+    # conda?
+    # - name: [WINDOWS,CONDA] Set up MSVC Compiler
+    #   uses: ilammy/msvc-dev-cmd@v1
+    #   if: matrix.install-method == 'conda' && matrix.os == 'windows-latest' && env.INSTALLC == 1
+    # This step and the next allows conda to be called before the
+    # conda-incubator/setup-miniconda@v2 action is used to create the
+    # test environment so that the package can be built in the base
+    # environment.
+    - name: [UNIX,CONDA] Add miniconda bin to path
+      if: matrix.install-method == 'conda' && matrix.os != 'windows-latest'
+      run: echo "PATH=$CONDA/bin:$PATH" >> $GITHUB_ENV
+    - name: [MACOS,CONDA] Change ownership of conda on MacOS
+      shell: bash
+      if: matrix.install-method == 'conda' && matrix.os == 'macos-latest'
+      run: sudo chown -R $(whoami) $CONDA
+    - name: [CONDA] Build package in base environment
+      if: matrix.install-method == 'conda'
+      shell: bash --noprofile --norc -eo pipefail {0}
+      run: python utils/setup_test_env.py build ${{ matrix.install-method }} --python ${{ matrix.python-version }}
+    - name: [CONDA] Set up miniconda test environment
+      uses: conda-incubator/setup-miniconda@v2
+      if: matrix.install-method == 'conda'
+      with:
+        # TODO: Move autoupdate into script?
+        # auto-update-conda: true
+        python-version: ${{ matrix.python-version }}
+        channels: conda-forge
+        use-only-tar-bz2: true
+        channel-priority: strict
+    - name: [MACOS,CONDA] Install old MacOSX SDK for compatibility with the conda llvm (7)
+      if: matrix.os == 'macos-latest' && matrix.install-method == 'conda'
+      run: ./utils/setup_old_mac_sdk.sh
+    - name: [CONDA] Install dependencies & package from existing build
+      if: matrix.install-method == 'conda'
+      run: python utils/setup_test_env.py install ${{ matrix.install-method }} --without-build
+    # ========================================================
+    
     - name: Verify installation
       run: python utils/setup_test_env.py verify
     - name: Compile libraries
@@ -130,65 +212,44 @@ jobs:
         ports:
           - 5672:5672
         options: --health-cmd "rabbitmqctl node_health_check" --health-interval 10s --health-timeout 5s --health-retries 5
-
-    steps:
-    - uses: actions/checkout@v2
-      with:
-        submodules: true
-    - name: Set up Python
-      uses: actions/setup-python@v2
-      if: matrix.install-method == 'pip'
-      with:
-        python-version: ${{ matrix.python-version }}
-    - name: Install dependencies
-      run: python utils/setup_test_env.py install ${{ matrix.install-method }}
-    - name: Verify installation
-      run: python utils/setup_test_env.py verify
-    - name: Compile libraries
-      run: yggcompile
-    - name: Run tests
-      run: yggtest --ci ${{ matrix.test-flags }}
-    - name: Upload coverage report
-      uses: codecov/codecov-action@v1
-    # - name: Start SSH session
-    #   uses: luchihoratiu/debug-via-ssh@main
-    #   if: ${{ failure() }}
-    #   with:
-    #     NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
-    #     SSH_PASS: ${{ secrets.SSH_PASS }}
-
-  build_conda:
-    name: Build (${{ matrix.python-version }}, ${{ matrix.os }}, ${{ matrix.install-method }})
-    runs-on: ${{ matrix.os }}
-    strategy:
-      max-parallel: 5
-      matrix:
-        os: [ubuntu-latest, macos-latest, windows-latest]
-        python-version: [3.6]
-        install-method: [conda]
-        test-flags: [--long-running]  # , --test-suite=examples]
-        include:
-          - os: ubuntu-latest
-            python-version: 3.8
-            install-method: conda
-      fail-fast: false
     defaults:
       run:
         shell: bash -l {0}
-    env:
-      GHA_SHELL: bash
 
     steps:
     - uses: actions/checkout@v2
       with:
         submodules: true
-    - name: Patch TEMP on Windows
+    - name: [WINDOWS] Patch TEMP on Windows
       if: matrix.os == 'windows-latest'
       run: |
         echo "TMPDIR=$USERPROFILE\AppData\Local\Temp" >> $GITHUB_ENV
         echo "TEMP=$USERPROFILE\AppData\Local\Temp" >> $GITHUB_ENV
-    - name: Cache conda
+    - name: [WINDOWS] Set up MSVC Compiler
+      uses: ilammy/msvc-dev-cmd@v1
+      if: matrix.os == 'windows-latest' && env.INSTALLC == 1
+      with:
+        toolset: 14.0
+	
+    # ========================================================
+    # Pip specific installation steps
+    # ========================================================
+    - name: [PIP] Set up Python for pip install
+      uses: actions/setup-python@v2
+      if: matrix.install-method == 'pip'
+      with:
+        python-version: ${{ matrix.python-version }}
+    - name: [PIP] Install dependencies & package
+      if: matrix.install-method == 'pip'
+      run: python utils/setup_test_env.py install ${{ matrix.install-method }}
+    # ========================================================
+    
+    # ========================================================
+    # Conda specific installation steps
+    # ========================================================
+    - name: [CONDA] Cache conda
       uses: actions/cache@v1
+      if: matrix.install-method == 'conda'
       env:
         # Increase this value to reset cache if file not changed
         CACHE_NUMBER: 0
@@ -197,38 +258,29 @@ jobs:
         key:
           ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{
           hashFiles('recipe/meta.yaml') }}
-    - name: Set up miniconda base environment on Windows
+    - name: [WINDOWS,CONDA] Set up miniconda base environment
       uses: conda-incubator/setup-miniconda@v2
       if: matrix.install-method == 'conda' && matrix.os == 'windows-latest'
       with:
         channels: conda-forge
         use-only-tar-bz2: true
         activate-environment: ''
-        # auto-activate-base: false
-    - name: Set up MSVC Compiler
-      uses: ilammy/msvc-dev-cmd@v1
-      if: matrix.os == 'windows-latest' && env.INSTALLC == 1
-    # - name: Record location of MSVC tools on Windows
-    #   if: matrix.os == 'windows-latest' && env.INSTALLC == 1
-    #   run: |
-    #     echo "YGG_LINK_PATH=$(which link.exe)" >> $GITHUB_ENV
-    #     echo "YGG_MSVC_BIN=$(dirname $(which link.exe))" >> $GITHUB_ENV
     # This step and the next allows conda to be called before the
-    # conda-incubator/setup-miniconda@v2 action is used to create the test
-    # environment so that the package can be built in the base environment.
-    - name: Add miniconda bin to path - Unix
+    # conda-incubator/setup-miniconda@v2 action is used to create the
+    # test environment so that the package can be built in the base
+    # environment.
+    - name: [UNIX,CONDA] Add miniconda bin to path
       if: matrix.install-method == 'conda' && matrix.os != 'windows-latest'
-      run: |
-        echo "PATH=$CONDA/bin:$PATH" >> $GITHUB_ENV
-    - name: Change ownership of conda on MacOS
-      shell: bash  # --noprofile --norc -eo pipefail {0}
-      if: matrix.os == 'macos-latest'
-      run: |
-        sudo chown -R $(whoami) $CONDA
-    - name: Build package
+      run: echo "PATH=$CONDA/bin:$PATH" >> $GITHUB_ENV
+    - name: [MACOS,CONDA] Change ownership of conda on MacOS
+      shell: bash
+      if: matrix.install-method == 'conda' && matrix.os == 'macos-latest'
+      run: sudo chown -R $(whoami) $CONDA
+    - name: [CONDA] Build package in base environment
+      if: matrix.install-method == 'conda'
       shell: bash --noprofile --norc -eo pipefail {0}
       run: python utils/setup_test_env.py build ${{ matrix.install-method }} --python ${{ matrix.python-version }}
-    - name: Set up miniconda test environment
+    - name: [CONDA] Set up miniconda test environment
       uses: conda-incubator/setup-miniconda@v2
       if: matrix.install-method == 'conda'
       with:
@@ -237,12 +289,15 @@ jobs:
         python-version: ${{ matrix.python-version }}
         channels: conda-forge
         use-only-tar-bz2: true
-        # channel-priority: strict
-    - name: Install old MacOSX SDK for compatibility with the conda llvm (7)
+        channel-priority: strict
+    - name: [MACOS,CONDA] Install old MacOSX SDK for compatibility with the conda llvm (7)
       if: matrix.os == 'macos-latest' && matrix.install-method == 'conda'
       run: ./utils/setup_old_mac_sdk.sh
-    - name: Install dependencies
+    - name: [CONDA] Install dependencies & package from existing build
+      if: matrix.install-method == 'conda'
       run: python utils/setup_test_env.py install ${{ matrix.install-method }} --without-build
+    # ========================================================
+    
     - name: Verify installation
       run: python utils/setup_test_env.py verify
     - name: Compile libraries
@@ -261,6 +316,118 @@ jobs:
     #   with:
     #     NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
     #     SSH_PASS: ${{ secrets.SSH_PASS }}
+
+  # build_conda:
+  #   name: Build (${{ matrix.python-version }}, ${{ matrix.os }}, ${{ matrix.install-method }})
+  #   runs-on: ${{ matrix.os }}
+  #   strategy:
+  #     max-parallel: 5
+  #     matrix:
+  #       os: [ubuntu-latest, macos-latest, windows-latest]
+  #       python-version: [3.6]
+  #       install-method: [conda]
+  #       test-flags: [--long-running]  # , --test-suite=examples]
+  #       include:
+  #         - os: ubuntu-latest
+  #           python-version: 3.8
+  #           install-method: conda
+  #     fail-fast: false
+  #   defaults:
+  #     run:
+  #       shell: bash -l {0}
+
+  #   steps:
+  #   - uses: actions/checkout@v2
+  #     with:
+  #       submodules: true
+  #   - name: [WINDOWS] Patch TEMP on Windows
+  #     if: matrix.os == 'windows-latest'
+  #     run: |
+  #       echo "TMPDIR=$USERPROFILE\AppData\Local\Temp" >> $GITHUB_ENV
+  #       echo "TEMP=$USERPROFILE\AppData\Local\Temp" >> $GITHUB_ENV
+  #   - name: Set up MSVC Compiler
+  #     uses: ilammy/msvc-dev-cmd@v1
+  #     if: matrix.os == 'windows-latest' && env.INSTALLC == 1
+	
+  #   # ========================================================
+  #   # Conda specific installation steps
+  #   # ========================================================
+  #   - name: [CONDA] Cache conda
+  #     uses: actions/cache@v1
+  #     if: matrix.install-method == 'conda'
+  #     env:
+  #       # Increase this value to reset cache if file not changed
+  #       CACHE_NUMBER: 0
+  #     with:
+  #       path: ~/conda_pkgs_dir
+  #       key:
+  #         ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{
+  #         hashFiles('recipe/meta.yaml') }}
+  #   - name: [WINDOWS,CONDA] Set up miniconda base environment
+  #     uses: conda-incubator/setup-miniconda@v2
+  #     if: matrix.install-method == 'conda' && matrix.os == 'windows-latest'
+  #     with:
+  #       channels: conda-forge
+  #       use-only-tar-bz2: true
+  #       activate-environment: ''
+  #       # auto-activate-base: false
+  #   # This step might need to stay here so that dev prompt comes before
+  #   # conda?
+  #   # - name: [WINDOWS,CONDA] Set up MSVC Compiler
+  #   #   uses: ilammy/msvc-dev-cmd@v1
+  #   #   if: matrix.install-method == 'conda' && matrix.os == 'windows-latest' && env.INSTALLC == 1
+  #   # This step and the next allows conda to be called before the
+  #   # conda-incubator/setup-miniconda@v2 action is used to create the
+  #   # test environment so that the package can be built in the base
+  #   # environment.
+  #   - name: [UNIX,CONDA] Add miniconda bin to path
+  #     if: matrix.install-method == 'conda' && matrix.os != 'windows-latest'
+  #     run: echo "PATH=$CONDA/bin:$PATH" >> $GITHUB_ENV
+  #   - name: [MACOS,CONDA] Change ownership of conda on MacOS
+  #     shell: bash
+  #     if: matrix.install-method == 'conda' && matrix.os == 'macos-latest'
+  #     run: sudo chown -R $(whoami) $CONDA
+  #   - name: [CONDA] Build package in base environment
+  #     if: matrix.install-method == 'conda'
+  #     shell: bash --noprofile --norc -eo pipefail {0}
+  #     run: python utils/setup_test_env.py build ${{ matrix.install-method }} --python ${{ matrix.python-version }}
+  #   - name: [CONDA] Set up miniconda test environment
+  #     uses: conda-incubator/setup-miniconda@v2
+  #     if: matrix.install-method == 'conda'
+  #     with:
+  #       # TODO: Move autoupdate into script?
+  #       # auto-update-conda: true
+  #       python-version: ${{ matrix.python-version }}
+  #       channels: conda-forge
+  #       use-only-tar-bz2: true
+  #       channel-priority: strict
+  #   - name: [MACOS,CONDA] Install old MacOSX SDK for compatibility with the conda llvm (7)
+  #     if: matrix.os == 'macos-latest' && matrix.install-method == 'conda'
+  #     run: ./utils/setup_old_mac_sdk.sh
+  #   - name: [CONDA] Install dependencies & package from existing build
+  #     if: matrix.install-method == 'conda'
+  #     run: python utils/setup_test_env.py install ${{ matrix.install-method }} --without-build
+  #   # ========================================================
+    
+  #   - name: Verify installation
+  #     run: python utils/setup_test_env.py verify
+  #   - name: Compile libraries
+  #     run: yggcompile
+  #   - name: Run tests
+  #     run: yggtest --ci ${{ matrix.test-flags }}
+  #   - name: Generate XML version of coverage report and check for coverage report
+  #     run: |
+  #       coverage xml
+  #       ls -la
+  #   - name: Upload coverage report
+  #     uses: codecov/codecov-action@v1
+  #   # - name: Start SSH session
+  #   #   uses: luchihoratiu/debug-via-ssh@main
+  #   #   if: ${{ failure() }}
+  #   #   with:
+  #   #     NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
+  #   #     SSH_PASS: ${{ secrets.SSH_PASS }}
+    
   docs:
     name: Build the Docs
     runs-on: ubuntu-latest
@@ -292,7 +459,7 @@ jobs:
         FOLDER: docs/build/html/
   deploy:
     name: Publish package
-    needs: [build_pip, build_conda, build_rmq, docs]
+    needs: [build_pip, build_rmq, docs]
     if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
     runs-on: ubuntu-latest
     steps:
